CREATE SCHEMA referencedata_tbls;

GRANT USAGE ON SCHEMA opendata_tbls TO referencedata_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA opendata_tbls TO referencedata_user;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA opendata_tbls TO referencedata_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA opendata_tbls GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO referencedata_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA opendata_tbls GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO referencedata_user;

SET search_path TO opendata_tbls;

/* Create Tables */

CREATE TABLE AIRPORTS
(
	IATA_CODE varchar(5) NOT NULL,
	AIRPORT_NAME varchar(50) NOT NULL,
	CITY varchar(50),
	COUNTRY varchar(50),
	KEY_NAME varchar(50),
	PRIMARY KEY (IATA_CODE)
);

CREATE SEQUENCE SEQ_TIMEZONES_COUNTRIES_ID START 100 INCREMENT BY 1;

CREATE TABLE TIMEZONES_COUNTRIES
(
	ID int DEFAULT nextval('SEQ_TIMEZONES_COUNTRIES_ID'),
	TIMEZONE_ID varchar(10),
	TIMEZONE varchar(50),
	DESCRIPTION varchar(250),
	CITY varchar(150),
	STATE_OR_TERRITORY varchar(150),
	COUNTRY varchar(150),
	CONSTRAINT PK_TIMEZONES_COUNTRIES__ID PRIMARY KEY (ID)
);

CREATE TABLE CITIES
(
	ISO_CODE varchar(5) NOT NULL,
	CITY_NAME varchar(50),
	DESCRIPTION varchar(1000),
	IS_METRO char(1),
	STATUS varchar(5),
	COUNTRY_CODE varchar(5) NOT NULL,
	TIMEZONE_CODE varchar(5),
	PRIMARY KEY (ISO_CODE)
);

CREATE TABLE COUNTRIES 
(
	ISO_CODE_ALPHA_2 varchar(5),
	ISO_CODE_ALPHA_3 varchar(5),
	ISO_CODE_NUMERIC varchar(5),
	COUNTRY_NAME varchar(50),
	CURRENCY_CODE varchar (5),
	ISD_CODE varchar(15),
	STATUS varchar(5),
	REGION_CODE varchar (50),
	PRIMARY KEY (ISO_CODE_ALPHA_2)
);


CREATE TABLE CURRENCIES
(
	ISO_CODE varchar(5) NOT NULL,
	CURRENCY_NAME varchar(50) NOT NULL,
	DESCRIPTION varchar(1000),
	ROUNDING NUMERIC(2,0),
	DECIMALS NUMERIC(2,0),
	STATUS varchar(5),
	PRIMARY KEY (ISO_CODE)
);


CREATE TABLE REGIONS
(
	CODE varchar(10) NOT NULL,
	REGION_NAME varchar(50) NOT NULL,
	DESCRIPTION varchar(1000),
	STATUS varchar(5),
	PRIMARY KEY (CODE)
);


CREATE TABLE TIMEZONES
(
	TIMEZONE_CODE varchar(5) NOT NULL,
	TIMEZONE_NAME varchar(50) NOT NULL,
	DESCRIPTION varchar(1000),
	GMT_VARIATION_MINUTES numeric(3,0) NOT NULL,
	STATUS varchar(5),
	PRIMARY KEY (TIMEZONE_CODE)
);


CREATE TABLE TIMEZONE_DST
(
	DST_ID varchar(5) NOT NULL,
	DST_NAME varchar(50) NOT NULL,
	DESCRIPTION varchar(1000),
	DST_START_DATE timestamp NOT NULL,
	DST_END_DATE timestamp NOT NULL,
	DST_VARIATION_MINUTES numeric(3,0) NOT NULL,
	STATUS varchar(5),
	PRIMARY KEY (DST_ID)
);

CREATE TABLE LOOKUP_COUNTRY
(
	ISO_CODE varchar(5) NOT NULL,
	COUNTRY_NAME varchar(50) NOT NULL,
	PRIMARY KEY (ISO_CODE, COUNTRY_NAME)
);

CREATE TABLE LOOKUP_CITY
(
	ISO_CODE varchar(5) NOT NULL,
	CITY_NAME varchar(100) NOT NULL,
	COUNTRY_CODE varchar(5)  NOT NULL,
	PRIMARY KEY (ISO_CODE, CITY_NAME)
);
