SET search_path TO opendata_tbls;

INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AAN', 'AL AIN ', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ADD', 'ADDIS ABABA', 'ET');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AHB', 'ABHA', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ALP', 'ALEPPO', 'SY');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ALY', 'ALEXANDRIA', 'EG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AMD', 'AHMEDABAD', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AMM', 'AMMAN', 'JO');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ASB', 'ASHGABAT', 'TM');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ATZ', 'ASSIUT', 'EG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AUH', 'ABU DHABI', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('AZI', 'ABU DHABI BATEEN', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('BAH', 'BAHRAIN', 'BH');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('BEG', 'BELGRADE', 'RS');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('BEY', 'BEIRUT', 'LB');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('BGW', 'BAGHDAD', 'IQ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('BSR', 'BASRA', 'IQ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('CGP', 'CHITTAGONG', 'BD');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('CJB', 'COIMBATORE', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('CMB', 'COLOMBO', 'LK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DAC', 'DHAKA', 'BD');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DAM', 'DAMASCUS', 'SY');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DEL', 'DELHI', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DJE', 'DJERBA', 'TN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DMM', 'DAMMAM', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DNK', 'DNEPROPETROVSK', 'UA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DOH', 'DOHA', 'QA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DOK', 'DONETSK', 'UA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DXB', 'DUBAI', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DYU', 'DUSHANBE', 'TJ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('EBL', 'ERBIL', 'IQ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ELQ', 'GASSIM', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('FRU', 'BISHKEK', 'KG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('GYD', 'BAKU', 'AZ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HAS', 'HAIL', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HBE', 'ALEXANDRIA', 'EG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HMB', 'SOHAG', 'EG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HOF', 'HOFUF AL AHSA', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HRI', 'HAMBANTOTA', 'LK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HRK', 'KHARKIV', 'UA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('HYD', 'HYDERABAD', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('IEV', 'KIEV ZHULYANY', 'UA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ISU', 'SULAIMANIYAH', 'IQ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('IXC', 'CHANDIGARH', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('JED', 'JEDDAH', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('JIB', 'DJIBOUTI', 'DJ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('JUB', 'JUBA', 'SS');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KBL', 'KABUL', 'AF');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KDH', 'KANDAHAR', 'AF');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KHI', 'KARACHI', 'PK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KIV', 'CHISINAU', 'MD');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KTM', 'KATHMANDU', 'NP');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KWI', 'KUWAIT', 'KW');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('KZN', 'KAZAN', 'RU');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('LKO', 'LUCKNOW', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('LTK', 'LATAKIA', 'SY');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('LXR', 'LUXOR', 'EG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('MCT', 'MUSCAT', 'OM');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('MED', 'MEDINA', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('MRV', 'MINERALNYYE VODY', 'RU');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('MUX', 'MUHAMMAD BIN QASIM', 'PK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('NJF', 'NAJAF', 'IQ');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('OAI', 'BAGRAM', 'AF');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('OAZ', 'CAMP BASTION', 'AF');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ODS', 'ODESSA', 'UA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('OSS', 'OSH', 'KG');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('OTP', 'BUCHAREST', 'RO');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('PZU', 'PORT SUDAN', 'SD');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('QAJ', 'AJMAN', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('RUH', 'RIYADH', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SAH', 'SANAA', 'YE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SAW', 'ISTANBUL', 'TR');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SHJ', 'SHARJAH', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SKP', 'SKOPJE', 'MK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SKT', 'SAILKOT', 'PK');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SLL', 'SALALAH', 'OM');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('SVX', 'YEKATERINBURG', 'RU');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('TBS', 'TBILISI', 'GE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('TIF', 'TAIF', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('TRV', 'THIRUVANANTHAPURAM', 'IN');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('TUU', 'TABUK', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('UFA', 'UFA', 'RU');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('VAS', 'SIVAS', 'TR');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('YNB', 'YANBU', 'SA');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('ZZZ', 'DUBAI BUS SERVICE', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DXB', 'Dubai', 'AE');
INSERT INTO lookup_city (iso_code, city_name, country_code) VALUES ('DXB', 'DXB', 'AE');

COMMIT;