SET search_path TO opendata_tbls;

INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('AA', 'American Airlines');
INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('BA', 'British Airways');
INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('LH', 'Lufthansa');
INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('LX', 'Swissair');
INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('OS', 'Austrian');
INSERT INTO AIRLINES (AIRLINE_CODE, AIRLINE_NAME) VALUES  ('SN', 'Brussels Airlines');
